ARG BUILD_IMAGE=

FROM ${BUILD_IMAGE}

ARG RUST_VERSION=1.42.0

ENV LANG=C.UTF-8

RUN mkdir /assets \
    && curl -L https://static.rust-lang.org/rustup/archive/${RUST_VERSION}/x86_64-unknown-linux-gnu/rustup-init -o rustup-init \
    && chmod +x rustup-init \
    && ./rustup-init -y --default-toolchain ${RUST_VERSION} --profile minimal \
    && cp -R --parents /root/.cargo /root/.rustup /usr/local/cargo /usr/local/rustup /assets
