ARG BUILD_IMAGE=

FROM ${BUILD_IMAGE}

ARG PHP_VERSION=7.4.3

ENV LANG=C.UTF-8

RUN mkdir /assets \
    && curl -L https://www.php.net/distributions/php-${PHP_VERSION}.tar.gz -o php-${PHP_VERSION}.tar.gz \
    && tar -xzf php-${PHP_VERSION}.tar.gz \
    && cd php-${PHP_VERSION} \
    && ./configure --prefix=/usr/local --enable-shared --with-openssl \
    && make -j "$(nproc)" \
    && make -j "$(nproc)" install \
    && cp -R --parents /usr/local/{bin,lib,include} /assets
